### ISSUE TITLE
Documentation: Moldoc 3D embeddings of molecules not working

### ISSUE THREAD

**Issue by CCEMGroupTCD** [CCEMGroupTCD/DARTassembler#2]
The 3D rotatable images of molecules by moldoc in the documentation don't show on ReadtheDocs, even though they do show on my local machine. There is just a white background.

**Comment by CCEMGroupTCD** [comment]
For now, I exluded the moldoc interactive images and instead included normal images. Also, I opened an issue on the moldocs page: https://github.com/lukasturcani/moldoc/issues/12

**Comment by TimoSommer** [comment]
Moldoc was fixed: https://github.com/lukasturcani/moldoc/issues/12

I updated the docs requirements for DARTassembler as moldoc>=3.0.5. The 2D images were again replaced by the moldoc 3D images. This issue is closed.
